### ISSUE TITLE
Fecha y Edad

### ISSUE THREAD

**Issue by Juli13130** [Juli13130/Test#3]
El profe literal nos desaprueba si usamos listas y operaciones para strings

Necesitamos una forma de convertir "YYYY-MM-DD" a edad

**Comment by keeevinj** [comment]
from datetime import datetime

def calcular_edad(fecha_nacimiento):
    # Convertir la cadena de fecha de nacimiento a un objeto datetime
    fecha_nacimiento = datetime.strptime(fecha_nacimiento, '%Y-%m-%d')
    
    # Obtener la fecha actual
    fecha_actual = datetime.now()
    
    # Calcular la diferencia de años entre la fecha actual y la fecha de nacimiento
    edad = fecha_actual.year - fecha_nacimiento.year
    
    # Ajustar la edad si aún no ha pasado el cumpleaños este año
    if (fecha_actual.month, fecha_actual.day) < (fecha_nacimiento.month, fecha_nacimiento.day):
        edad = edad - 1
    
    return edad

# Ejemplo de uso
fecha_nacimiento = "2000-05-12"
edad = calcular_edad(fecha_nacimiento)
print("La edad es:", edad)

Ya lo modifique y agregué
