### ISSUE TITLE
Ver candidatos

### ISSUE THREAD

**Issue by Juli13130** [Juli13130/Test#4]
al ingresar a esta opción, se deben mostrar todos los estudiantes. Mostrar nombre, fecha de nacimiento, edad, biografía y hobbies. Una vez mostrada toda la información, permitir ingresar en una variable me-gusta el nombre del estudiante con el cual le gustaría en un futuro hacer un Matcheo. Verificar que el nombre sea correcto

El verificar se puede hacer con un while ■■ is not ●● and ○○ and □□

La variable me-gusta probablemente debería ser metida en un print en el menú anterior y creo que solo debería contener la string del nombre

**Comment by keeevinj** [comment]
Agregué la visualización de candidatos. Queda ver eso de la variable me gusta

**Comment by keeevinj** [comment]
Se arregló con la nueva feature de matriz de likes.
